### ISSUE TITLE
Having trouble taking readings outside of 'setInterval'

### ISSUE THREAD

**Issue by egalpin** [rjd22/nodejs-adcpi#1]
Hi there,

Thanks for your the work on nodejs-adcpi.  I've hit an interesting snag.  Consider the following code snippet:

```
var MCP3424 = require('mcp3424'),
address = 0x6E,
gain = 0,
resolution = 3,
mcp = new MCP3424(address, gain, resolution, '/dev/i2c-1');

console.log(mcp.getMv(0));
setInterval(function() {
    console.log(mcp.getMv(0));
}, 1000);
```

The output will be as follows:

```
undefined
2047.984375
2047.984375
...
```

Note the `undefined`.  Any idea what I might be doing wrong to end up with undefined outside of the `setInterval`?

Thanks!

**Comment by rjd22** [comment]
Sometimes it will give a undefined because it could not do a reading or the ADC is not ready for reading yet. The best you can do is filter those out.
